name: Check Directory Commit Date

on:
  push:
    branches:
      - main

jobs:
  check_directory_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        DIRECTORY="target/linux/ath79"
        THRESHOLD_SECONDS=$((24 * 60 * 60))  # 24 Stunden in Sekunden

        # Hole alle Commits für den Hauptbranch
        COMMITS=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA")

        # Suche nach Commits, die das betreffende Verzeichnis betreffen
        LAST_COMMIT=$(echo "$COMMITS" | jq --arg DIRECTORY "$DIRECTORY" -r '.[] | select(.files[]? | .filename | startswith($DIRECTORY)) | .commit.author.date')

        if [ -n "$LAST_COMMIT" ]; then
          LAST_COMMIT_TIMESTAMP=$(date -d "$LAST_COMMIT" +"%s")
          CURRENT_TIMESTAMP=$(date +"%s")
          DIFF_SECONDS=$((CURRENT_TIMESTAMP - LAST_COMMIT_TIMESTAMP))

          if [ $DIFF_SECONDS -le $THRESHOLD_SECONDS ]; then
            echo "Das Verzeichnis $DIRECTORY wurde im letzten Commit innerhalb der letzten 24 Stunden geändert. Fortsetzen..."
            # Füge hier den Code für den Fall ein, dass das Verzeichnis im letzten Commit innerhalb der letzten 24 Stunden geändert wurde.
          else
            echo "Das Verzeichnis $DIRECTORY wurde im letzten Commit mehr als 24 Stunden zurück geändert. Abbrechen..."
            exit 1
          fi
        else
          echo "Das Verzeichnis $DIRECTORY wurde im letzten Commit nicht gefunden. Abbrechen..."
          exit 1
        fi
